### PR TITLE
Fix removal of system attachments

### LINKED ISSUE #70: Bug: removing attachments whose keys start with $ fails
### Describe the bug
Calling `Bucket::remove_attachments` (and the helper APIs that call it under the hood) with an attachment key that starts with `$` always fails. The SDK builds the Mongo-style filter with a `$in` condition but never escapes the values before serializing them, so a key such as `$system` is sent as `"$$system"`. ReductStore treats that as the `$$system` operator and responds with a 422 instead of removing the attachment.

### To Reproduce
1. Run ReductStore 1.18.5 or 1.19.0 locally (observed with both docker tags `reduct/store:latest` and `reduct/store:main`).
2. Using the current `reduct-rs` crate, create a bucket and write a record that has two attachments, e.g. `"frames"` and `"$system"`.
3. Call `bucket.remove_attachments("test-record", &["frames", "$system"]).await?`.
4. The request fails with `Status 422: Operator '$$system' not supported` and nothing is removed.

### Expected behavior
All requested attachments—including those whose keys start with `$`—should be removed successfully.

### Additional context
reduct-py PR #163 fixes the same bug in the Python SDK by escaping the attachment keys before constructing the `$in` condition. The Rust SDK uses the same approach and needs the same escaping so that `$system` (and similar) attachments can be removed.

### PR DESCRIPTION
**Pull request by mother-6000**
Closes #70

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Bug fix.

### What was changed?

- Escape attachment keys that begin with `$` before constructing the `$in` filter so that ReductStore treats them as literals instead of operators.
- Extend the attachment-removal tests to cover `$system` keys (both combined with normal attachments and on their own).
- Add the regression note to the Unreleased changelog.

### Related issues

- #70

### Does this PR introduce a breaking change?

No.

### Other information:

Verification:
- `cargo fmt --all`
- `cargo check`

Integration tests that exercise attachment removal require a running ReductStore instance (per AGENTS.md); Docker is not available in this environment, so those were not executed here.

### CODE REVIEW

File: src/bucket/attachments.rs [hunk 1]
```diff
@@ -96,7 +96,17 @@ impl Bucket {
 
         let query = if let Some(keys) = attachment_keys {
             let mut when = vec![json!({"&key": {"$cast": "string"}})];
-            when.extend(keys.into_iter().map(Value::from));
+            let escaped_keys = keys
```
Comment (atimin) [inline src/bucket/attachments.rs:101]: add short comment

**Review by atimin — CHANGES_REQUESTED** [review]

**Review by atimin — CHANGES_REQUESTED** [review]
All commits must be signed.

**Review by atimin — APPROVED** [review]
